# fly.toml file generated for morning-hill-2249 on 2023-02-26T16:06:35-06:00

app = "morning-hill-2249"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  auto_rollback = true
